language: go

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t flagbitgmbh/analytics_exporter:latest .
  - docker push flagbitgmbh/analytics_exporter:latest
